const PathConstants = {
  TELALOGIN: "/",
  LISTAITENS: "/listaitens",
  CADASTROITENS: "/cadastroitens",
  LISTAMODELOS: "/listamodelos",
  CADASTROMODELOS: "/cadastromodelos/:especifique",
  LISTAFABRICANTES: "/listafabricantes",
  CADASTROFABRICANTES: "/cadastrofabricantes",
  LISTATIPO: "/listatipos",
  CADASTROTIPO: "/cadastrotipos/:especifique",
  EDITARTIPO: "/editartipos/:especifique/:idgenerico",
  LISTASETOR: "/listasetores",
  CADASTROSETOR: "/cadastrosetores/:especifique",
  EDITARSETOR: "/editarsetores/:especifique/:idgenerico",
  LISTASITUACAO: "/listasituacoes",
  CADASTROSITUACAO: "/cadastrosituacoes/:especifique",
  EDITARSITUACAO: "/editarsituacoes/:especifique/:idgenerico",
  LISTAUSUARIO: "/listausuarios",
  CADASTROUSUARIO: "/cadastrousuarios",
  LISTAGENERCICA: "/listagenerica/:especifique",
  CADASTROGENERICO: "/cadastrogenerico/:especifique",
  EDITARITEM: "/editaritem/:especifique",
  EDITARMODELO: "/editarmodelos/:idgenerico",
  EDITARFABRICANTE: "/editarfabricante/:especifique",
  EDITARUSUARIO: "/editarusuario/:especifique",
  RELATORIOHIST: "/relatoriohist",
};

export default PathConstants;
